logging:
    file: target/${spring.application.name}.log
    level:
        ROOT: INFO
        org.ylzl.eden: DEBUG

spring:
    application:
        name: #project.name#
    data:
        redis:
            repositories:
                enabled: true
    jmx:
        default-domain: ${spring.application.name}
    mvc:
        favicon:
            enabled: false
    profiles:
        active: #spring.profiles.active#
        include: #spring.profiles.include#
    redis:
        host: 127.0.0.1
        port: 6379
        password: DevOps@303
        database: 0
        timeout: 5000
        pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
            max-wait: -1
